
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

//import javafx.embed.swing.JFXPanel;
//import javafx.scene.media.Media;
//import javafx.scene.media.MediaPlayer;

import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Marin
 */
public class Formulario extends javax.swing.JDialog {

    /**
     * Creates new form Formulario
     */
    public Formulario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initMisComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_tema = new javax.swing.JTextField();
        lblTema = new javax.swing.JLabel();
        lblAutor = new javax.swing.JLabel();
        tf_autor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tf_album = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_nuevo = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_borrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_canciones = new javax.swing.JTable();
        btn_limpiar = new javax.swing.JButton();
        btn_escuchar = new javax.swing.JButton();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblTema.setText("Tema");

        lblAutor.setText("Autor");

        jLabel1.setText("Album");

        jLabel2.setText("Año");

        btn_nuevo.setText("Nuevo");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });

        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        btn_borrar.setText("Borrar");
        btn_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrarActionPerformed(evt);
            }
        });

        tbl_canciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_canciones);

        btn_limpiar.setText("Limpiar");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        btn_escuchar.setText("Escuchar");
        btn_escuchar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_escucharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAutor)
                            .addComponent(lblTema)
                            .addComponent(tf_tema, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                            .addComponent(tf_autor))
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jYearChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_escuchar))
                                .addComponent(tf_album, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(btn_nuevo)
                .addGap(51, 51, 51)
                .addComponent(btn_modificar)
                .addGap(61, 61, 61)
                .addComponent(btn_borrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_limpiar)
                .addGap(212, 212, 212))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTema)
                    .addComponent(jLabel1))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_tema, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(tf_album))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAutor)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_escuchar)
                    .addComponent(tf_autor, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jYearChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_limpiar)
                    .addComponent(btn_nuevo)
                    .addComponent(btn_modificar)
                    .addComponent(btn_borrar))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        insertarRegistroTabla();
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        modificarRegistroTabla(tbl_canciones.getSelectedRow());
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrarActionPerformed
        borrarRegistroTabla(tbl_canciones.getSelectedRow());
    }//GEN-LAST:event_btn_borrarActionPerformed

    private void btn_escucharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_escucharActionPerformed

        Ecualizador ecualizador = new Ecualizador(this, false);
        ecualizador.setVisible(true);
    }//GEN-LAST:event_btn_escucharActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        guardarDatos();
    }//GEN-LAST:event_formWindowClosing

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        limpiar_campos();
    }//GEN-LAST:event_btn_limpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Formulario dialog = new Formulario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        //guardarDatos();
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_borrar;
    private javax.swing.JButton btn_escuchar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblTema;
    private javax.swing.JTable tbl_canciones;
    private javax.swing.JTextField tf_album;
    private javax.swing.JTextField tf_autor;
    private javax.swing.JTextField tf_tema;
    // End of variables declaration//GEN-END:variables
    
    public static DefaultTableModel modelo = new DefaultTableModel();
    //final JFXPanel fxPanel = new JFXPanel();
    //private static MediaPlayer mediaPlayer; // Se crea el mediaPlayer estatico para que la musica no se pare por el Garbage
    
    //Metodo para guardarTabla al finalizar la ejecución
    
    public  ArrayList<String> transformarTabla (){
        
        ArrayList<String> datos = new ArrayList<>();
        
        for (int i=0; i< modelo.getRowCount();i++){
            String linea = "";
            for( int j=0; j<modelo.getColumnCount();j++){
                linea+=modelo.getValueAt(i, j)+";";
            }
            datos.add(linea);
        }
        
        return datos;
    }
    
    
    
    public void cargarTabla(){
        ArrayList<String> datos = new ArrayList<>();
        datos = AccesoADatos.leerDatosFichero();
        for (int i=0; i<datos.size();i++){
            String linea = datos.get(i);
            String[] registros = linea.split(";");
            modelo.addRow(registros);
            
        }
    }
    
    public boolean insertarRegistroTabla(){  // metodo a usar con el boton nuevo
        // metodo que recoja los 4 registros de los campos del formulario e inserte en tabla
        // Llamar a validar campos primero if(!validarCampos) return false;
        if (validar_campos()){
            String tema = tf_tema.getText();
            String autor = tf_autor.getText();
            String album = tf_album.getText();
            String anno = String.valueOf(jYearChooser1.getValue());
        
            String[] registros = {tema, autor, album, anno};
        
            modelo.addRow(registros);
        
            limpiar_campos();
            return true;
        }
        return false;
    }
    
    public void borrarRegistroTabla(int row){ // Metodo boton borrar
        if (row!=-1){
            modelo.removeRow(row);
        }
    }
    
    public boolean modificarRegistroTabla(int row){
        //Llamar a validar campos primero if(!validarCampos) return false
        if (validar_campos()){
            if (row!=-1){
                String tema = tf_tema.getText();
                String autor = tf_autor.getText();
                String album = tf_album.getText();
                String anno = String.valueOf(jYearChooser1.getValue());
                String[] registros = {tema, autor, album, anno};
                modelo.removeRow(row);
                modelo.insertRow(row, registros);
                limpiar_campos();
            }else{
                return false;
        }
        return true;
        }
        return false;
    }
    
    private void iniciarTabla(){
        
        modelo = new DefaultTableModel();
        modelo.addColumn("Titulo");
        modelo.addColumn("Autor");
        modelo.addColumn("Album");
        modelo.addColumn("Año publicación");
        
        tbl_canciones.setModel(modelo);
        
        cargarTabla();
        
        
        
    }
    
    
    
//    public void ReproducirSonidoMP3(String ruta) {
//        
//        Media hit = new Media(new File(ruta).toURI().toString()) {};
//        mediaPlayer = new MediaPlayer(hit);
//        mediaPlayer.play();
//}

    private void initMisComponentes() {
        iniciarTabla();
        
    }
    
    private  void guardarDatos(){
        ArrayList<String> datos;
        datos = transformarTabla();
        AccesoADatos.escribirDatosFichero(datos);
    }

    private void limpiar_campos() {
        tf_album.setText("");
        
        tf_autor.setText("");
        tf_tema.setText("");
    }
    
    private boolean validar_campos(){
        if ((tf_tema.getText()==null)||(tf_tema.getText().contentEquals(""))){
            JOptionPane.showMessageDialog(null, "Debes escribir un nombre en el campo Tema");
            return false;
        }
        if ((tf_album.getText()==null)||(tf_album.getText().contentEquals(""))){
            JOptionPane.showMessageDialog(null, "Debes escribir un nombre en el campo Album");
            return false;
        }
        if ((tf_autor.getText()==null)||(tf_autor.getText().contentEquals(""))){
            JOptionPane.showMessageDialog(null, "Debes escribir un nombre en el campo Autor");
            return false;
        }
        
        return true;
    }
    
}     
    

    




